#!/usr/bin/env node
import assert from 'node:assert/strict';
import fs from 'node:fs';
import path from 'node:path';
import vm from 'node:vm';
const ROOT=process.cwd(),MODE=(process.argv.find(x=>x==='--full'||x==='--frontend-only')||'--frontend-only').slice(2);let passed=0;
function file(p){const x=path.join(ROOT,p);assert.ok(fs.existsSync(x),'missing file: '+p);return fs.readFileSync(x,'utf8')}
function ok(name,fn){try{fn();passed++;console.log('ok '+passed+' - '+name)}catch(e){console.error('not ok - '+name);throw e}}
function scripts(html){const out=[];for(const m of html.matchAll(/<script\b([^>]*)>([\s\S]*?)<\/script\s*>/gi)){const a=m[1]||'',type=(a.match(/\btype=["']([^"']+)["']/i)||[])[1]||'';if(/\bsrc\s*=/.test(a)||type&&!/(?:javascript|ecmascript|module)/i.test(type))continue;const b=(m[2]||'').replace(/<\?(?:!=|=)?[\s\S]*?\?>/g,'null');if(b.trim())out.push(b)}return out}
const index=file('frontend/index.html'),config=file('frontend/app-config.js'),transport=file('frontend/cloud-run-transport.js'),gateway=file('cloud-run-gateway/server.js'),cloudWorkflow=file('.github/workflows/cloud-run-gateway.yml'),frontWorkflow=file('.github/workflows/frontend-validation.yml');
ok('CR-7 repository layout is Cloud Run source-only',()=>{assert.ok(fs.existsSync(path.join(ROOT,'frontend')));assert.ok(!fs.existsSync(path.join(ROOT,'github-pages')));assert.ok(!fs.existsSync(path.join(ROOT,'.github/workflows/pages.yml')));assert.deepEqual(fs.readdirSync(path.join(ROOT,'frontend')).sort(),['app-config.js','cloud-run-transport.js','index.html'])});
ok('frontend has no GitHub Pages or direct GAS runtime dependency',()=>{const all=index+'\n'+config+'\n'+transport;for(const token of ['sapa27.github.io','github-pages','github-gas-transport','APP_GITHUB_CONFIG','GAS_WEB_APP_URL','script.google.com'])assert.ok(!all.includes(token),'retired runtime token: '+token)});
ok('Cloud Run frontend identity is canonical',()=>{assert.ok(index.includes('CANONICAL CLOUD RUN FRONTEND r331-v62'));assert.ok(index.includes('"hostMode":"cloud-run"'));assert.ok(index.includes('./cloud-run-transport.js?v=r331-v62-cloudrun-cr7-20260918'));assert.ok(config.includes('cloud-run-canonical-frontend-r331-v62-cr7-runtime-decoupled-20260918'));assert.ok(config.includes('APP_RUNTIME_CONFIG'));assert.ok(config.includes('cloud-run-direct-json-v1'))});
ok('frontend JavaScript syntax',()=>{new vm.Script(config);new vm.Script(transport);scripts(index).forEach((s,i)=>new vm.Script(s,{filename:'index#'+(i+1)}))});
ok('critical application surfaces remain present',()=>{for(const id of ['dashboard','search','petitioner','meeting','committee-meeting','track','report','people','budget','admin'])assert.ok(index.includes('tpl-page-'+id),'missing '+id);for(const marker of ['ลำดับเรื่อง','จัดการเรื่องพิจารณา','ประวัติการประชุม','หนังสือติดตามมติ'])assert.ok(index.includes(marker),'missing UI marker '+marker)});
ok('CR-5 mobile Meeting protections remain in CR-7',()=>{assert.ok(index.includes('id="app-mobile-compact-cr5"'));assert.ok(index.includes('route.meeting.bootstrap-background:'));assert.ok(index.includes('forceFresh:!1,assetStamp:'));assert.ok(!index.includes('forceFresh:/^Scripts_Page_Meeting'))});
ok('CR-6 data-loading fixes remain in CR-7',()=>{assert.ok(index.includes('function expandAssetList(list)'));assert.ok(index.includes('loadActualFiles(core,"core")'));assert.ok(!index.includes('safePartial("bundle:appCore")'));assert.ok(transport.includes('wire==="apiRouter"'));assert.ok(transport.includes('write=isWriteMethod(I.method),read=isReadMethod(I.method)'));assert.ok(transport.includes('EPOCH++'));assert.ok(transport.includes('epoch===EPOCH'));assert.ok(transport.includes('stale-while-revalidate'))});
ok('browser transport is Cloud Run only',()=>{assert.ok(transport.includes('cloud-run-direct-json-cr7'));assert.ok(transport.includes('u+"/api/router"'));assert.ok(transport.includes('credentials:"omit"'));assert.ok(transport.includes('cache:"no-store"'));assert.ok(!transport.includes('parentOrigin'));assert.ok(!transport.includes('rpcToken'));assert.ok(!transport.includes('rpcVersion'))});
ok('gateway supports CR-7 transition without browser GitHub dependency',()=>{new vm.Script(gateway);assert.ok(gateway.includes("REV='cr7-runtime-decoupled-r330'"));assert.ok(gateway.includes("transport:'gas-direct-json'"));assert.ok(gateway.includes("transport:'legacy-rpc-fallback'"));assert.ok(gateway.includes("c.legacyEnabled?'server-rpc-compat':'direct-json-primary'"));assert.ok(!gateway.includes("env.GAS_PARENT_ORIGIN"))});
ok('Cloud Run workflow stages frontend not Pages',()=>{assert.ok(cloudWorkflow.includes("cp -R frontend cloud-run-gateway/public"));assert.ok(cloudWorkflow.includes("'frontend/**'"));assert.ok(!cloudWorkflow.includes("'github-pages/**'"));assert.ok(cloudWorkflow.includes("v.gasTransport!==\"server-rpc-compat\""));assert.ok(cloudWorkflow.includes("Probe GAS RPC with Cloud Run parent origin"));assert.ok(frontWorkflow.includes("node .github/tests/regression.mjs --frontend-only"))});
ok('frontend config keeps bounded read caches and timeouts',()=>{for(const x of ['REQUEST_TIMEOUT_MS:45000','WRITE_REQUEST_TIMEOUT_MS:120000','AI_DOCUMENT_TIMEOUT_MS:300000','RPC_READ_CACHE_MAX_ENTRIES:96','apiGetDashboardBundle:180000','apiGetMeetingLookupOptions:300000'])assert.ok(config.includes(x),x)});
console.log('# '+passed+' CR-7 regression groups passed ('+MODE+')');
