'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),{once}=require('node:events');
const {REV,cfg,gasUrl,allowed,isWrite,timeout,createServer}=require('../server');
const ORIGIN='https://sapa27-gateway-asxuzzwspa-eu.a.run.app';
const ENV={GAS_WEB_APP_URL:'https://script.google.com/macros/s/AKfycbwXIRMjP4yKRRlS7loJFiAmVCLxKq_uie6rUPsaKw17wtzWQOkjjaH2ah8gIqsHA6_G/exec',GATEWAY_ALLOWED_ORIGINS:ORIGIN};
async function withServer(fn,env=ENV){const server=createServer(env);server.listen(0,'127.0.0.1');await once(server,'listening');try{return await fn('http://127.0.0.1:'+server.address().port)}finally{await new Promise(r=>server.close(r))}}
test('CR-7 configuration is Cloud Run direct-primary',()=>{const c=cfg(ENV);assert.equal(REV,'cr7-runtime-decoupled-r330');assert.equal(c.legacyEnabled,false);assert.equal(gasUrl(ENV.GAS_WEB_APP_URL),ENV.GAS_WEB_APP_URL);assert.equal(allowed(ORIGIN,c),true);assert.equal(isWrite('apiSaveCase'),true);assert.equal(isWrite('apiGetDashboardBundle'),false);assert.equal(timeout('apiGetDashboardBundle',999999,c),45000)});
test('readiness/version expose decoupled transport',async()=>withServer(async base=>{const r=await(await fetch(base+'/ready')).json(),v=await(await fetch(base+'/version')).json();assert.equal(r.gateway,'cr7-runtime-decoupled-r330');assert.equal(r.gasTransport,'direct-json-primary');assert.equal(v.frontendHost,'cloud-run');assert.equal(v.gasTransport,'direct-json-primary')}));
test('CORS accepts Cloud Run origin and rejects unknown origin',async()=>withServer(async base=>{const denied=await fetch(base+'/api/router',{method:'OPTIONS',headers:{Origin:'https://evil.invalid'}});assert.equal(denied.status,403);const ok=await fetch(base+'/api/router',{method:'OPTIONS',headers:{Origin:ORIGIN}});assert.equal(ok.status,204);assert.equal(ok.headers.get('access-control-allow-origin'),ORIGIN)}));
test('API route uses direct JSON GAS POST',async()=>{const browserFetch=global.fetch,calls=[];global.fetch=async(url,opt={})=>{calls.push({url:String(url),opt});return{ok:true,status:200,text:async()=>JSON.stringify({ok:true,data:{rows:[1]}})}};try{await withServer(async base=>{const res=await browserFetch(base+'/api/router',{method:'POST',headers:{Origin:ORIGIN,'Content-Type':'application/json'},body:JSON.stringify({method:'apiGetDashboardBundle',payload:{}})});const out=await res.json();assert.equal(out.ok,true);assert.equal(out.meta.transport,'gas-direct-json');assert.ok(calls.some(x=>x.opt&&x.opt.headers&&x.opt.headers['Content-Type']==='application/json;charset=UTF-8'))})}finally{global.fetch=browserFetch}});
