'use strict';
const http=require('node:http'),crypto=require('node:crypto'),fs=require('node:fs'),path=require('node:path');
const NAME='sapa27-cloud-run-gateway',REV='cr7-runtime-decoupled-r330',PUBLIC_DIR=path.join(__dirname,'public');
const txt=v=>v==null?'':String(v),sleep=ms=>new Promise(r=>setTimeout(r,ms));
function yes(v){return /^(1|true|yes|y|on)$/i.test(txt(v).trim())}
function cfg(env=process.env){const origins=txt(env.GATEWAY_ALLOWED_ORIGINS||'').split(',').map(x=>x.trim()).filter(Boolean);return{port:+env.PORT||8080,gas:txt(env.GAS_WEB_APP_URL),origins,read:+env.GAS_READ_TIMEOUT_MS||45000,write:+env.GAS_WRITE_TIMEOUT_MS||120000,ai:+env.GAS_AI_TIMEOUT_MS||300000,maxBody:+env.MAX_BODY_BYTES||8388608,legacyEnabled:yes(env.LEGACY_GAS_RPC_FALLBACK||''),legacyRpc:txt(env.LEGACY_GAS_RPC_VERSION),legacyParent:txt(env.LEGACY_GAS_PARENT_ORIGIN)}}
function gasUrl(v){try{const u=new URL(v);if(u.protocol!=='https:'||u.hostname!=='script.google.com'||!/^\/macros\/s\/[A-Za-z0-9_-]+\/exec$/.test(u.pathname))return'';return u.origin+u.pathname}catch(_){return''}}
function requestHost(req){return txt(req.headers['x-forwarded-host']||req.headers.host).split(',')[0].trim().toLowerCase()}
function sameOrigin(req,o){if(!o)return false;try{return new URL(o).host.toLowerCase()===requestHost(req)}catch(_){return false}}
function allowed(o,c,req){return!!o&&(c.origins.includes(o)||!!req&&sameOrigin(req,o))}
const cors=(o,c,req)=>({'Access-Control-Allow-Origin':allowed(o,c,req)?o:'null','Access-Control-Allow-Methods':'GET,POST,OPTIONS','Access-Control-Allow-Headers':'Content-Type,X-Request-ID','Access-Control-Max-Age':'600','Vary':'Origin'});
function send(res,status,obj,h={}){const b=JSON.stringify(obj);res.writeHead(status,{'Content-Type':'application/json; charset=utf-8','Cache-Control':'no-store','X-Content-Type-Options':'nosniff','Content-Length':Buffer.byteLength(b),...h});res.end(b)}
function fail(msg,code='GATEWAY_ERROR',status=502){const e=new Error(msg);e.code=code;e.status=status;return e}
const id=p=>p+'_'+crypto.randomBytes(18).toString('hex');
const isWrite=m=>/^api(?:(?!Get|List|Search|Check).)*(Save|Delete|Update|Queue|Process|Create|Migrate|Repair|Cleanup|Import)/.test(m),isAI=m=>/^apiExtract(?:Tracking|Document|MeetingAgenda)Pdf$/i.test(m);
function timeout(method,want,c){const cap=isAI(method)?c.ai:isWrite(method)?c.write:c.read,n=+want||cap;return Math.max(10000,Math.min(cap,n))}
async function ftimeout(url,opt,ms){const ac=new AbortController(),t=setTimeout(()=>ac.abort(),ms);try{return await fetch(url,{...opt,signal:ac.signal})}catch(e){if(e.name==='AbortError')throw fail('GAS upstream timeout','GAS_UPSTREAM_TIMEOUT',504);throw e}finally{clearTimeout(t)}}
async function directRpc(method,payload,want,c){if(!/^[A-Za-z][A-Za-z0-9_]{1,127}$/.test(method))throw fail('Invalid API method','METHOD_INVALID',400);const g=gasUrl(c.gas);if(!g)throw fail('GAS_WEB_APP_URL is not configured','GAS_URL_NOT_CONFIGURED',503);const started=Date.now(),r=await ftimeout(g,{method:'POST',redirect:'follow',headers:{'Content-Type':'application/json;charset=UTF-8','Accept':'application/json'},body:JSON.stringify({method,payload:payload==null?{}:payload})},timeout(method,want,c));if(!r.ok)throw fail('GAS direct HTTP '+r.status,'GAS_DIRECT_HTTP_'+r.status,r.status>=500?502:400);const raw=await r.text();let result;try{result=JSON.parse(raw)}catch(_){throw fail('GAS direct response is not JSON','GAS_DIRECT_JSON_INVALID',502)}return{ok:true,result,meta:{gateway:REV,method,transport:'gas-direct-json',durationMs:Date.now()-started}}}
function parseJsonp(body,cb){const s=txt(body).trim(),p='/**/'+cb+'(';if(!s.startsWith(p)||!s.endsWith(');'))throw fail('Invalid GAS legacy JSONP','GAS_LEGACY_JSONP_INVALID');try{return JSON.parse(s.slice(p.length,-2))}catch(_){throw fail('Invalid GAS legacy JSONP payload','GAS_LEGACY_JSONP_PARSE_FAILED')}}
async function legacyJsonp(mode,params,ms,c){if(!c.legacyEnabled||!c.legacyRpc||!c.legacyParent)throw fail('Legacy GAS RPC fallback disabled','GAS_LEGACY_DISABLED',503);const g=gasUrl(c.gas),cb='__legacyRpcCb_'+Date.now().toString(36)+'_'+crypto.randomBytes(6).toString('hex'),u=new URL(g);u.searchParams.set('mode',mode);for(const[k,v]of Object.entries(params||{}))u.searchParams.set(k,txt(v));u.searchParams.set('callback',cb);u.searchParams.set('_ts',Date.now().toString(36));const r=await ftimeout(u,{redirect:'follow'},ms);if(!r.ok)throw fail('GAS legacy JSONP HTTP '+r.status,'GAS_LEGACY_JSONP_HTTP');return parseJsonp(await r.text(),cb)}
function legacyInvoke(method,payload){if(/^(apiLogin|apiSessionResume|apiSessionCheck|apiLogout|getDeferredInclude)$/.test(method))return{fn:method,args:payload||{},orig:method};return{fn:'apiRouter',args:{method,payload:payload||{}},orig:method}}
async function legacyRpc(method,payload,want,c){const call=legacyInvoke(method,payload),now=Date.now(),deadline=now+timeout(call.orig,want,c),rec={rid:id('req'),tok:id('tok'),trace:id('trace')},form=new URLSearchParams({mode:'github-rpc',parentOrigin:c.legacyParent,rpcVersion:c.legacyRpc,rpcId:rec.rid,rpcToken:rec.tok,rpcFunction:call.fn,rpcPayload:JSON.stringify(call.args),traceId:rec.trace,clientStartedAt:new Date(now).toISOString()}),g=gasUrl(c.gas);const post=ftimeout(g,{method:'POST',redirect:'follow',headers:{'Content-Type':'application/x-www-form-urlencoded;charset=UTF-8'},body:form},Math.min(45000,deadline-Date.now())).then(r=>{if(!r.ok)throw fail('GAS legacy POST HTTP '+r.status,'GAS_LEGACY_POST_HTTP')});let attempt=0;const poll=(async()=>{await sleep(100);while(Date.now()<deadline){attempt++;const left=deadline-Date.now();let x;try{x=await legacyJsonp('github-rpc-result',{parentOrigin:c.legacyParent,rpcVersion:c.legacyRpc,rpcId:rec.rid,rpcToken:rec.tok},Math.max(3000,Math.min(30000,left)),c)}catch(e){if(Date.now()>=deadline-1000)throw e;await sleep(Math.min(1200,250+attempt*220));continue}if(x&&x.pending===true){await sleep(Math.min(1200,250+attempt*220));continue}if(!x||x.transportOk===false||x.ok===false){const e=x&&x.error||{};throw fail(txt(e.message||e.error)||'GAS legacy RPC failed',txt(e.code||e.errorCode)||'GAS_LEGACY_RPC_FAILED')}return{ok:true,result:x.result,meta:{gateway:REV,method:call.orig,transport:'legacy-rpc-fallback',durationMs:Date.now()-now,pollAttempts:attempt}}}throw fail('GAS legacy RPC timeout: '+call.orig,'GAS_LEGACY_RPC_TIMEOUT',504)})();return Promise.race([poll,post.then(()=>new Promise(()=>{}),e=>Promise.reject(e))])}
async function rpc(method,payload,want,c){if(c.legacyEnabled)return legacyRpc(method,payload,want,c);return directRpc(method,payload,want,c)}
function body(req,max){return new Promise((resolve,reject)=>{let n=0,a=[];req.on('data',x=>{n+=x.length;if(n>max){reject(fail('Request too large','REQUEST_TOO_LARGE',413));req.destroy()}else a.push(x)});req.on('end',()=>{try{const s=Buffer.concat(a).toString('utf8').trim();resolve(s?JSON.parse(s):{})}catch(_){reject(fail('Invalid JSON','INVALID_JSON',400))}});req.on('error',reject)})}
const MIME={'.html':'text/html; charset=utf-8','.js':'text/javascript; charset=utf-8','.css':'text/css; charset=utf-8','.json':'application/json; charset=utf-8','.svg':'image/svg+xml','.png':'image/png','.jpg':'image/jpeg','.jpeg':'image/jpeg','.gif':'image/gif','.webp':'image/webp','.ico':'image/x-icon','.txt':'text/plain; charset=utf-8','.pdf':'application/pdf'};
function staticFile(urlPath){let p;try{p=decodeURIComponent(urlPath)}catch(_){return null}if(p==='/'||p==='')p='/index.html';const rel=path.posix.normalize(p).replace(/^\/+/, '');if(!rel||rel.startsWith('..')||rel.includes('/../'))return null;const full=path.resolve(PUBLIC_DIR,rel);if(!full.startsWith(path.resolve(PUBLIC_DIR)+path.sep)&&full!==path.resolve(PUBLIC_DIR))return null;return full}
function serveStatic(req,res,u){if(req.method!=='GET'&&req.method!=='HEAD')return false;let full=staticFile(u.pathname);if(!full)return false;try{let st=fs.statSync(full);if(st.isDirectory()){full=path.join(full,'index.html');st=fs.statSync(full)}if(!st.isFile())return false;const ext=path.extname(full).toLowerCase(),base=path.basename(full),noStore=ext==='.html'||base==='app-config.js'||base==='cloud-run-transport.js';const h={'Content-Type':MIME[ext]||'application/octet-stream','Content-Length':st.size,'Cache-Control':noStore?'no-store':'public, max-age=300','X-Content-Type-Options':'nosniff'};res.writeHead(200,h);if(req.method==='HEAD')return res.end(),true;fs.createReadStream(full).pipe(res);return true}catch(_){return false}}
function createServer(env=process.env){const c=cfg(env);return http.createServer(async(req,res)=>{const u=new URL(req.url||'/','http://local'),o=txt(req.headers.origin),ch=cors(o,c,req),trace=txt(req.headers['x-request-id'])||id('http');try{if(req.method==='OPTIONS'){if(!allowed(o,c,req))throw fail('Origin not allowed','ORIGIN_NOT_ALLOWED',403);res.writeHead(204,{...ch,'Content-Length':'0'});return res.end()}if(req.method==='GET'&&u.pathname==='/ready')return send(res,200,{ok:true,service:NAME,gateway:REV,frontend:fs.existsSync(path.join(PUBLIC_DIR,'index.html')),gasTransport:c.legacyEnabled?'server-rpc-compat':'direct-json-primary',legacyFallbackEnabled:c.legacyEnabled,cloudRun:{service:txt(env.K_SERVICE),revision:txt(env.K_REVISION)}});if(req.method==='GET'&&u.pathname==='/version')return send(res,200,{ok:true,service:NAME,gateway:REV,frontendHost:'cloud-run',gasTransport:c.legacyEnabled?'server-rpc-compat':'direct-json-primary',legacyFallbackEnabled:c.legacyEnabled,cloudRun:{service:txt(env.K_SERVICE),revision:txt(env.K_REVISION)}});if(req.method==='GET'&&u.pathname==='/health'){const x=await rpc('apiSessionCheck',{},Math.min(c.read,30000),c);return send(res,200,{ok:true,service:NAME,gateway:REV,upstream:{ok:true,transport:x.meta&&x.meta.transport,degraded:!!(x.meta&&x.meta.degraded),directErrorCode:txt(x.meta&&x.meta.directErrorCode)},traceId:trace},allowed(o,c,req)?ch:{})}if(u.pathname==='/api'||u.pathname==='/api/router'){if(req.method!=='POST')throw fail('Method not allowed','METHOD_NOT_ALLOWED',405);if(!allowed(o,c,req))throw fail('Origin not allowed','ORIGIN_NOT_ALLOWED',403);const b=await body(req,c.maxBody),out=await rpc(txt(b.method).trim(),b.payload==null?{}:b.payload,b.timeoutMs,c);out.meta.httpTraceId=trace;return send(res,200,out,ch)}if(serveStatic(req,res,u))return;throw fail('Not found','NOT_FOUND',404)}catch(e){const status=+e.status||500;console.warn(JSON.stringify({severity:status>=500?'ERROR':'WARNING',service:NAME,gateway:REV,traceId:trace,path:u.pathname,code:txt(e.code),message:txt(e.message)}));return send(res,status,{ok:false,error:{code:txt(e.code)||'GATEWAY_ERROR',message:txt(e.message)||'Gateway error'},traceId:trace,gateway:REV},allowed(o,c,req)?ch:{})}})}
function start(env=process.env){const c=cfg(env),s=createServer(env);s.listen(c.port,'0.0.0.0',()=>console.log(JSON.stringify({severity:'INFO',service:NAME,gateway:REV,port:c.port,upstreamConfigured:!!gasUrl(c.gas),gasTransport:c.legacyEnabled?'server-rpc-compat':'direct-json-primary',legacyFallbackEnabled:c.legacyEnabled,frontend:fs.existsSync(path.join(PUBLIC_DIR,'index.html'))})));process.on('SIGTERM',()=>s.close(()=>process.exit(0)));return s}
if(require.main===module)start();
module.exports={NAME,REV,PUBLIC_DIR,cfg,gasUrl,allowed,sameOrigin,isWrite,timeout,directRpc,legacyRpc,rpc,staticFile,serveStatic,createServer};
