'use strict';
const http=require('node:http'),fs=require('node:fs'),path=require('node:path'),crypto=require('node:crypto');
const NAME='sapa27-cloud-run-gateway',REV='cr7-runtime-decoupled-r330',PUBLIC_DIR=path.join(__dirname,'public');
const txt=v=>v==null?'':String(v);
function sourceSha(env=process.env){return txt(env.APP_SOURCE_SHA).trim()}
function cfg(env=process.env){return{port:+env.PORT||8080,gas:txt(env.GAS_WEB_APP_URL),origins:txt(env.GATEWAY_ALLOWED_ORIGINS||'').split(',').map(x=>x.trim()).filter(Boolean),read:+env.GAS_READ_TIMEOUT_MS||45000,write:+env.GAS_WRITE_TIMEOUT_MS||120000,ai:+env.GAS_AI_TIMEOUT_MS||300000,maxBody:+env.MAX_BODY_BYTES||8388608}}
function gasUrl(v){try{const u=new URL(v);if(u.protocol!=='https:'||u.hostname!=='script.google.com'||!/^\/macros\/s\/[A-Za-z0-9_-]+\/exec$/.test(u.pathname))return'';return u.origin+u.pathname}catch(_){return''}}
function requestHost(req){return txt(req.headers['x-forwarded-host']||req.headers.host).split(',')[0].trim().toLowerCase()}
function sameOrigin(req,o){if(!o)return false;try{return new URL(o).host.toLowerCase()===requestHost(req)}catch(_){return false}}
function allowed(o,c,req){return!!o&&(c.origins.includes(o)||sameOrigin(req,o))}
function cors(o,c,req){return{'Access-Control-Allow-Origin':allowed(o,c,req)?o:'null','Access-Control-Allow-Methods':'GET,POST,OPTIONS','Access-Control-Allow-Headers':'Content-Type,X-Request-ID','Access-Control-Max-Age':'600','Vary':'Origin'}}
function send(res,status,obj,h={}){const b=JSON.stringify(obj);res.writeHead(status,{'Content-Type':'application/json; charset=utf-8','Cache-Control':'no-store','X-Content-Type-Options':'nosniff','Content-Length':Buffer.byteLength(b),...h});res.end(b)}
function fail(message,code='GATEWAY_ERROR',status=502){const e=new Error(message);e.code=code;e.status=status;return e}
const isWrite=m=>/^api(?:(?!Get|List|Search|Check).)*(Save|Delete|Update|Queue|Process|Create|Migrate|Repair|Cleanup|Import)/.test(txt(m));
const isAI=m=>/^apiExtract(?:Tracking|Document|MeetingAgenda)Pdf$/i.test(txt(m));
function timeout(method,want,c){const cap=isAI(method)?c.ai:isWrite(method)?c.write:c.read,n=+want||cap;return Math.max(10000,Math.min(cap,n))}
async function ftimeout(url,opt,ms){const ac=new AbortController(),timer=setTimeout(()=>ac.abort(),ms);try{return await fetch(url,{...opt,signal:ac.signal})}catch(e){if(e&&e.name==='AbortError')throw fail('GAS upstream timeout','GAS_UPSTREAM_TIMEOUT',504);throw e}finally{clearTimeout(timer)}}
async function directRpc(method,payload,want,c){method=txt(method).trim();if(!/^[A-Za-z][A-Za-z0-9_]{1,127}$/.test(method))throw fail('Invalid API method','METHOD_INVALID',400);const g=gasUrl(c.gas);if(!g)throw fail('GAS_WEB_APP_URL is not configured','GAS_URL_NOT_CONFIGURED',503);const started=Date.now();const r=await ftimeout(g,{method:'POST',redirect:'follow',headers:{'Content-Type':'application/json;charset=UTF-8','Accept':'application/json'},body:JSON.stringify({method,payload:payload==null?{}:payload})},timeout(method,want,c));if(!r.ok)throw fail('GAS direct HTTP '+r.status,'GAS_DIRECT_HTTP_'+r.status,r.status>=500?502:400);const raw=await r.text();let result;try{result=JSON.parse(raw)}catch(_){throw fail('GAS direct response is not JSON','GAS_DIRECT_JSON_INVALID',502)}if(result&&result.transportOk===false){const x=result.error||{};throw fail(txt(x.message||x.error)||'GAS direct call failed',txt(x.code||x.errorCode)||'GAS_DIRECT_FAILED',502)}const value=result&&result.transportOk===true&&Object.prototype.hasOwnProperty.call(result,'result')?result.result:result;return{ok:true,result:value,meta:{gateway:REV,method,transport:'gas-direct-json',durationMs:Date.now()-started}}}
function body(req,max){return new Promise((resolve,reject)=>{let n=0,chunks=[];req.on('data',x=>{n+=x.length;if(n>max){reject(fail('Request too large','REQUEST_TOO_LARGE',413));req.destroy()}else chunks.push(x)});req.on('end',()=>{try{const s=Buffer.concat(chunks).toString('utf8').trim();resolve(s?JSON.parse(s):{})}catch(_){reject(fail('Invalid JSON','INVALID_JSON',400))}});req.on('error',reject)})}
const MIME={'.html':'text/html; charset=utf-8','.js':'text/javascript; charset=utf-8','.css':'text/css; charset=utf-8','.json':'application/json; charset=utf-8','.svg':'image/svg+xml','.png':'image/png','.jpg':'image/jpeg','.jpeg':'image/jpeg','.gif':'image/gif','.webp':'image/webp','.ico':'image/x-icon','.txt':'text/plain; charset=utf-8','.pdf':'application/pdf'};
function staticFile(urlPath){let p;try{p=decodeURIComponent(urlPath)}catch(_){return null}if(!p||p==='/')p='/index.html';const rel=path.posix.normalize(p).replace(/^\/+/, '');if(!rel||rel.startsWith('..')||rel.includes('/../'))return null;const root=path.resolve(PUBLIC_DIR),full=path.resolve(PUBLIC_DIR,rel);if(full!==root&&!full.startsWith(root+path.sep))return null;return full}
function serveStatic(req,res,u){if(req.method!=='GET'&&req.method!=='HEAD')return false;let full=staticFile(u.pathname);if(!full)return false;try{let st=fs.statSync(full);if(st.isDirectory()){full=path.join(full,'index.html');st=fs.statSync(full)}if(!st.isFile())return false;const ext=path.extname(full).toLowerCase(),base=path.basename(full),noStore=ext==='.html'||base==='app-config.js'||base==='cloud-run-transport.js';res.writeHead(200,{'Content-Type':MIME[ext]||'application/octet-stream','Content-Length':st.size,'Cache-Control':noStore?'no-store':'public, max-age=300','X-Content-Type-Options':'nosniff'});if(req.method==='HEAD'){res.end();return true}fs.createReadStream(full).pipe(res);return true}catch(_){return false}}
function createServer(env=process.env){const c=cfg(env);return http.createServer(async(req,res)=>{const u=new URL(req.url||'/','http://local'),origin=txt(req.headers.origin),ch=cors(origin,c,req),trace=txt(req.headers['x-request-id'])||'http_'+crypto.randomBytes(12).toString('hex');try{if(req.method==='OPTIONS'){if(!allowed(origin,c,req))throw fail('Origin not allowed','ORIGIN_NOT_ALLOWED',403);res.writeHead(204,{...ch,'Content-Length':'0'});return res.end()}if(req.method==='GET'&&u.pathname==='/ready')return send(res,200,{ok:true,service:NAME,gateway:REV,sourceSha:sourceSha(env),frontend:fs.existsSync(path.join(PUBLIC_DIR,'index.html')),gasTransport:'direct-json-primary',legacyFallbackEnabled:false,cloudRun:{service:txt(env.K_SERVICE),revision:txt(env.K_REVISION)}});if(req.method==='GET'&&u.pathname==='/version')return send(res,200,{ok:true,service:NAME,gateway:REV,sourceSha:sourceSha(env),frontendHost:'cloud-run',gasTransport:'direct-json-primary',legacyFallbackEnabled:false,cloudRun:{service:txt(env.K_SERVICE),revision:txt(env.K_REVISION)}});if(req.method==='GET'&&u.pathname==='/health')return send(res,200,{ok:true,service:NAME,gateway:REV,status:'healthy',frontend:fs.existsSync(path.join(PUBLIC_DIR,'index.html')),upstream:{checked:false,transport:'gas-direct-json'},traceId:trace},allowed(origin,c,req)?ch:{});if(req.method==='GET'&&u.pathname==='/upstream-health'){const x=await directRpc('apiSessionCheck',{},10000,c);return send(res,200,{ok:true,service:NAME,gateway:REV,upstream:{checked:true,ok:true,transport:x.meta.transport,durationMs:x.meta.durationMs},traceId:trace},allowed(origin,c,req)?ch:{})}if(u.pathname==='/api'||u.pathname==='/api/router'){if(req.method!=='POST')throw fail('Method not allowed','METHOD_NOT_ALLOWED',405);if(!allowed(origin,c,req))throw fail('Origin not allowed','ORIGIN_NOT_ALLOWED',403);const b=await body(req,c.maxBody),out=await directRpc(txt(b.method),b.payload==null?{}:b.payload,b.timeoutMs,c);out.meta.httpTraceId=trace;return send(res,200,out,ch)}if(serveStatic(req,res,u))return;throw fail('Not found','NOT_FOUND',404)}catch(e){const status=+e.status||500;console.warn(JSON.stringify({severity:status>=500?'ERROR':'WARNING',service:NAME,gateway:REV,traceId:trace,path:u.pathname,code:txt(e.code),message:txt(e.message)}));return send(res,status,{ok:false,error:{code:txt(e.code)||'GATEWAY_ERROR',message:txt(e.message)||'Gateway error'},traceId:trace,gateway:REV},allowed(origin,c,req)?ch:{})}})}
function start(env=process.env){const c=cfg(env),server=createServer(env);server.listen(c.port,'0.0.0.0',()=>console.log(JSON.stringify({severity:'INFO',service:NAME,gateway:REV,port:c.port,upstreamConfigured:!!gasUrl(c.gas),gasTransport:'direct-json-primary',legacyFallbackEnabled:false,sourceSha:sourceSha(env),frontend:fs.existsSync(path.join(PUBLIC_DIR,'index.html'))})));process.on('SIGTERM',()=>server.close(()=>process.exit(0)));return server}
if(require.main===module)start();
module.exports={NAME,REV,PUBLIC_DIR,sourceSha,cfg,gasUrl,allowed,sameOrigin,isWrite,timeout,directRpc,staticFile,serveStatic,createServer};
