'use strict';
const http=require('node:http'),crypto=require('node:crypto');
const NAME='sapa27-cloud-run-gateway',REV='cr0-rpc-r330';
const txt=v=>v==null?'':String(v),sleep=ms=>new Promise(r=>setTimeout(r,ms));
function cfg(env=process.env){const origins=txt(env.GATEWAY_ALLOWED_ORIGINS||'https://sapa27.github.io').split(',').map(x=>x.trim()).filter(Boolean);return{port:+env.PORT||8080,gas:txt(env.GAS_WEB_APP_URL),rpc:txt(env.GAS_RPC_VERSION||'github-pages-rpc-r330'),parent:txt(env.GAS_PARENT_ORIGIN||'https://sapa27.github.io'),origins,read:+env.GAS_READ_TIMEOUT_MS||45000,write:+env.GAS_WRITE_TIMEOUT_MS||120000,ai:+env.GAS_AI_TIMEOUT_MS||300000,maxBody:+env.MAX_BODY_BYTES||8388608}}
function gasUrl(v){try{const u=new URL(v);if(u.protocol!=='https:'||u.hostname!=='script.google.com'||!/^\/macros\/s\/[A-Za-z0-9_-]+\/exec$/.test(u.pathname))return'';return u.origin+u.pathname}catch(_){return''}}
const allowed=(o,c)=>!!o&&c.origins.includes(o);
const cors=(o,c)=>({'Access-Control-Allow-Origin':allowed(o,c)?o:'null','Access-Control-Allow-Methods':'GET,POST,OPTIONS','Access-Control-Allow-Headers':'Content-Type,X-Request-ID','Access-Control-Max-Age':'600','Vary':'Origin'});
function send(res,status,obj,h={}){const b=JSON.stringify(obj);res.writeHead(status,{'Content-Type':'application/json; charset=utf-8','Cache-Control':'no-store','X-Content-Type-Options':'nosniff','Content-Length':Buffer.byteLength(b),...h});res.end(b)}
function fail(msg,code='GATEWAY_ERROR',status=502){const e=new Error(msg);e.code=code;e.status=status;return e}
const id=p=>p+'_'+crypto.randomBytes(18).toString('hex');
function invoke(method,payload){if(method==='apiRouter')return{fn:method,args:payload||{},orig:txt(payload&&payload.method)||method};if(/^(apiLogin|apiSessionResume|apiSessionCheck|apiLogout|getDeferredInclude)$/.test(method))return{fn:method,args:payload||{},orig:method};return{fn:'apiRouter',args:{method,payload:payload||{}},orig:method}}
const isWrite=m=>/^api(?:(?!Get|List|Search|Check).)*(Save|Delete|Update|Queue|Process|Create|Migrate|Repair|Cleanup|Import)/.test(m),isAI=m=>/^apiExtract(?:Tracking|Document|MeetingAgenda)Pdf$/i.test(m);
function timeout(method,want,c){const cap=isAI(method)?c.ai:isWrite(method)?c.write:c.read,n=+want||cap;return Math.max(10000,Math.min(cap,n))}
async function ftimeout(url,opt,ms){const ac=new AbortController(),t=setTimeout(()=>ac.abort(),ms);try{return await fetch(url,{...opt,signal:ac.signal})}catch(e){if(e.name==='AbortError')throw fail('GAS upstream timeout','GAS_UPSTREAM_TIMEOUT',504);throw e}finally{clearTimeout(t)}}
function parseJsonp(body,cb){const s=txt(body).trim(),p='/**/'+cb+'(';if(!s.startsWith(p)||!s.endsWith(');'))throw fail('Invalid GAS JSONP','GAS_JSONP_INVALID');try{return JSON.parse(s.slice(p.length,-2))}catch(_){throw fail('Invalid GAS JSONP payload','GAS_JSONP_PARSE_FAILED')}}
async function jsonp(mode,params,ms,c){const g=gasUrl(c.gas);if(!g)throw fail('GAS_WEB_APP_URL is not configured','GAS_URL_NOT_CONFIGURED',503);const cb='__ghRpcCb_cr_'+Date.now().toString(36)+'_'+crypto.randomBytes(6).toString('hex'),u=new URL(g);u.searchParams.set('mode',mode);for(const[k,v]of Object.entries(params||{}))u.searchParams.set(k,txt(v));u.searchParams.set('callback',cb);u.searchParams.set('_ts',Date.now().toString(36));const r=await ftimeout(u,{redirect:'follow'},ms);if(!r.ok)throw fail('GAS JSONP HTTP '+r.status,'GAS_JSONP_HTTP');return parseJsonp(await r.text(),cb)}
async function health(c){const x=await jsonp('github-rpc-health',{parentOrigin:c.parent,rpcVersion:c.rpc},15000,c);if(!x||x.ok!==true||x.allowedOrigin!==true)throw fail('GAS health denied','GAS_HEALTH_DENIED');if(txt(x.transportVersion)!==c.rpc)throw fail('GAS RPC version mismatch','GAS_RPC_VERSION_MISMATCH');return x}
async function rpc(method,payload,want,c){if(!/^[A-Za-z][A-Za-z0-9_]{1,127}$/.test(method))throw fail('Invalid API method','METHOD_INVALID',400);const call=invoke(method,payload),now=Date.now(),deadline=now+timeout(call.orig,want,c),rec={rid:id('req'),tok:id('tok'),trace:id('trace')},form=new URLSearchParams({mode:'github-rpc',parentOrigin:c.parent,rpcVersion:c.rpc,rpcId:rec.rid,rpcToken:rec.tok,rpcFunction:call.fn,rpcPayload:JSON.stringify(call.args),traceId:rec.trace,clientStartedAt:new Date(now).toISOString()}),g=gasUrl(c.gas);if(!g)throw fail('GAS_WEB_APP_URL is not configured','GAS_URL_NOT_CONFIGURED',503);const post=ftimeout(g,{method:'POST',redirect:'follow',headers:{'Content-Type':'application/x-www-form-urlencoded;charset=UTF-8'},body:form},Math.min(45000,deadline-Date.now())).then(r=>{if(!r.ok)throw fail('GAS RPC POST HTTP '+r.status,'GAS_RPC_POST_HTTP')});let attempt=0;const poll=(async()=>{await sleep(100);while(Date.now()<deadline){attempt++;const left=deadline-Date.now();let x;try{x=await jsonp('github-rpc-result',{parentOrigin:c.parent,rpcVersion:c.rpc,rpcId:rec.rid,rpcToken:rec.tok},Math.max(3000,Math.min(30000,left)),c)}catch(e){if(Date.now()>=deadline-1000)throw e;await sleep(Math.min(1200,250+attempt*220));continue}if(x&&x.pending===true){await sleep(Math.min(1200,250+attempt*220));continue}if(!x||x.transportOk===false||x.ok===false){const e=x&&x.error||{};throw fail(txt(e.message||e.error)||'GAS RPC failed',txt(e.code||e.errorCode)||'GAS_RPC_FAILED')}return{ok:true,result:x.result,meta:{gateway:REV,method:call.orig,traceId:rec.trace,durationMs:Date.now()-now,pollAttempts:attempt,rpcVersion:c.rpc}}}throw fail('GAS RPC request timeout: '+call.orig,'GAS_RPC_REQUEST_TIMEOUT',504)})();const postFailure=post.then(()=>new Promise(()=>{}),e=>Promise.reject(e));return Promise.race([poll,postFailure])}
function body(req,max){return new Promise((resolve,reject)=>{let n=0,a=[];req.on('data',x=>{n+=x.length;if(n>max){reject(fail('Request too large','REQUEST_TOO_LARGE',413));req.destroy()}else a.push(x)});req.on('end',()=>{try{const s=Buffer.concat(a).toString('utf8').trim();resolve(s?JSON.parse(s):{})}catch(_){reject(fail('Invalid JSON','INVALID_JSON',400))}});req.on('error',reject)})}
function createServer(env=process.env){const c=cfg(env);return http.createServer(async(req,res)=>{const u=new URL(req.url||'/','http://local'),o=txt(req.headers.origin),ch=cors(o,c),trace=txt(req.headers['x-request-id'])||id('http');try{if(req.method==='OPTIONS'){if(!allowed(o,c))throw fail('Origin not allowed','ORIGIN_NOT_ALLOWED',403);res.writeHead(204,{...ch,'Content-Length':'0'});return res.end()}if(req.method==='GET'&&(u.pathname==='/'||u.pathname==='/ready'))return send(res,200,{ok:true,service:NAME,gateway:REV,rpcVersion:c.rpc,upstreamConfigured:!!gasUrl(c.gas),cloudRun:{service:txt(env.K_SERVICE),revision:txt(env.K_REVISION)}});if(req.method==='GET'&&u.pathname==='/health'){const x=await health(c);return send(res,200,{ok:true,service:NAME,gateway:REV,rpcVersion:c.rpc,upstream:{ok:true,transportVersion:x.transportVersion},traceId:trace},allowed(o,c)?ch:{})}if(u.pathname==='/api'||u.pathname==='/api/router'){if(req.method!=='POST')throw fail('Method not allowed','METHOD_NOT_ALLOWED',405);if(!allowed(o,c))throw fail('Origin not allowed','ORIGIN_NOT_ALLOWED',403);const b=await body(req,c.maxBody),out=await rpc(txt(b.method).trim(),b.payload==null?{}:b.payload,b.timeoutMs,c);out.meta.httpTraceId=trace;return send(res,200,out,ch)}throw fail('Not found','NOT_FOUND',404)}catch(e){const status=+e.status||500;console.warn(JSON.stringify({severity:status>=500?'ERROR':'WARNING',service:NAME,gateway:REV,traceId:trace,path:u.pathname,code:txt(e.code),message:txt(e.message)}));return send(res,status,{ok:false,error:{code:txt(e.code)||'GATEWAY_ERROR',message:txt(e.message)||'Gateway error'},traceId:trace,gateway:REV},allowed(o,c)?ch:{})}})}
function start(env=process.env){const c=cfg(env),s=createServer(env);s.listen(c.port,'0.0.0.0',()=>console.log(JSON.stringify({severity:'INFO',service:NAME,gateway:REV,port:c.port,rpcVersion:c.rpc,upstreamConfigured:!!gasUrl(c.gas)})));process.on('SIGTERM',()=>s.close(()=>process.exit(0)));return s}
if(require.main===module)start();
module.exports={NAME,REV,cfg,gasUrl,allowed,invoke,isWrite,timeout,parseJsonp,createServer,rpc};
