(function(root){"use strict";
var existing=root.APP_CONFIG||{};
var GAS_URL="https://script.google.com/macros/s/AKfycbxu2K3ukqReIC8wCalO7P3NRrySO3JUVDoE3d4P0oEzknHehos1u7sCPeeYkashRzgV/exec";
var LOGO="https://upload.wikimedia.org/wikipedia/commons/9/9a/Seal_of_the_Parliament_of_Thailand.svg";
var RELEASE="commission-github-gas-r280-pending-reason-guard-2026-08-13";
var ASSET_VERSION="r280";
root.APP_GITHUB_CONFIG={GAS_WEB_APP_URL:GAS_URL,STATIC_LOGO_URL:LOGO,BRIDGE_MODE:"github-bridge",BRIDGE_TIMEOUT_MS:12000,REQUEST_TIMEOUT_MS:90000,API_TRANSPORT_MODE:"bridge-first",AUTH_TRANSPORT_MODE:"bridge-first",AUTH_POST_FALLBACK_TIMEOUT_MS:15000,API_POST_FALLBACK_TIMEOUT_MS:20000,BRIDGE_VERSION:"github-pages-bridge-v2",LOCAL_ASSET_MODE:false,LOCAL_ASSET_VERSION:ASSET_VERSION,DEFERRED_ASSET_VERSION:ASSET_VERSION,DEFERRED_ASSET_FORCE_FRESH:true};
root.APP_CONFIG=Object.assign({},existing,{appTitle:"ระบบบริหารจัดการเรื่องพิจารณา",version:"1.2.0-r280",releaseStamp:RELEASE,hostingTarget:"github-pages",transportMode:"github-pages-gas-router-bridge-first",gasWebAppUrl:GAS_URL,gasWebAppUrlServerEnvRequired:false,gasBackendUiDisabled:false,staticGasDirectDisabled:false,logoUrl:LOGO,fallbackLogoUrl:LOGO,bridgeTimeoutMs:12000,requestTimeoutMs:90000,clientReadResponseCacheEnabled:false,clientInFlightDedupe:true,clientApiCacheOwner:"none",clientInFlightOwner:"github-pages/github-gas-transport.js::r260-apps-script-origin-trust",deferredAssetVersion:ASSET_VERSION,deferredAssetForceFresh:true,pendingReasonCompatibilityGuard:true});
root.APP_DEPLOY_RELEASE=Object.assign({},root.APP_DEPLOY_RELEASE||{},{stamp:RELEASE,version:root.APP_CONFIG.version,source:"github-pages/app-config.js",transportMode:root.APP_CONFIG.transportMode,hostingTarget:root.APP_CONFIG.hostingTarget,githubPagesGasBridge:true,bridgeVersion:"github-pages-bridge-v2",deferredAssetVersion:ASSET_VERSION});
root.GAS_WEB_APP_URL=GAS_URL;root.APP_FALLBACK_LOGO_URL=LOGO;root.DEFAULT_LOGO=root.DEFAULT_LOGO||LOGO;root.LOGO_URL=root.LOGO_URL||LOGO;

/* r280 GitHub-only compatibility guard.
 * GAS r278 already renders เหตุผล for pending cases. This guard is intentionally
 * no-op when that canonical row exists; it only repairs a stale GitHub renderer.
 */
(function installPendingReasonGuard(w,d){
  if(!w||!d||w.__GITHUB_PENDING_REASON_GUARD_R280__)return;
  w.__GITHUB_PENDING_REASON_GUARD_R280__=true;
  var inflight=Object.create(null),resolved=Object.create(null),scheduled=false;
  var REASON_KEYS=["pendingReason","pendingRemark","waitReason","waitingReason","statusReason","decisionReason","reason","เหตุผล","เหตุผลรอพิจารณา","เหตุผลรอการพิจารณา","หมายเหตุรอพิจารณา","หมายเหตุรอการพิจารณา","remark","note","หมายเหตุ"];
  function text(v){return v==null?"":String(v).trim()}
  function pick(o,keys){if(!o||typeof o!=="object")return"";for(var i=0;i<keys.length;i++){var v=text(o[keys[i]]);if(v)return v}return""}
  function nestedObjects(o){var out=[];if(o&&typeof o==="object"){out.push(o);["raw","__raw","rawCase","case","detail","main","MainData","mainData","data","record","row"].forEach(function(k){var v=o[k];v&&typeof v==="object"&&out.indexOf(v)<0&&out.push(v)})}return out}
  function caseObject(bundle){var cur=bundle||{},seen=[];for(var i=0;i<8&&cur&&typeof cur==="object";i++){if(seen.indexOf(cur)>=0)break;seen.push(cur);if(cur.case&&typeof cur.case==="object")return cur.case;if(cur.detail&&typeof cur.detail==="object")return cur.detail;if(cur.main&&typeof cur.main==="object")return cur.main;if(cur.record&&typeof cur.record==="object")return cur.record;if(cur.row&&typeof cur.row==="object")return cur.row;if(cur.data&&typeof cur.data==="object"){cur=cur.data;continue}break}return cur&&typeof cur==="object"?cur:{}}
  function bundleNow(){try{if(w.AppStore&&typeof w.AppStore.get==="function")return w.AppStore.get("reportTrack.currentBundle",null)||w.AppStore.get("search.currentBundle",null)||w.__REPORT_TRACK_CURRENT_BUNDLE__||null}catch(_e){}return w.__REPORT_TRACK_CURRENT_BUNDLE__||null}
  function reasonFrom(bundle){var c=caseObject(bundle),objs=nestedObjects(c).concat(nestedObjects(bundle));for(var i=0;i<objs.length;i++){var v=pick(objs[i],REASON_KEYS);if(v)return v}return""}
  function statusFrom(bundle){var c=caseObject(bundle),objs=nestedObjects(c).concat(nestedObjects(bundle)),keys=["status","สถานะ","สถานะเรื่อง","currentStatus","caseStatus","statusText"];for(var i=0;i<objs.length;i++){var v=pick(objs[i],keys);if(v)return v}return""}
  function caseNumFrom(bundle){var c=caseObject(bundle),objs=nestedObjects(c).concat(nestedObjects(bundle)),keys=["caseNum","caseNo","runningNo","ลำดับเรื่อง"];for(var i=0;i<objs.length;i++){var v=pick(objs[i],keys);if(v)return v}return text(w.__REPORT_TRACK_CURRENT_CASE_ID__||w.__CURRENT_CASE_ID__||"")}
  function isPending(v){v=text(v).replace(/\s+/g,"");return v==="รอพิจารณา"||v==="รอการพิจารณา"}
  function statusSection(){var s=d.querySelector('#pdf-content [data-case-section="status"],#summary-view [data-case-section="status"]');if(s)return s;var cards=d.querySelectorAll("#pdf-content .case-official-card,#summary-view .case-official-card");for(var i=0;i<cards.length;i++){var t=cards[i].querySelector(".case-official-title");if(t&&text(t.textContent)==="สถานะเรื่อง")return cards[i]}return null}
  function rowByLabel(section,label){var labels=section?section.querySelectorAll(".case-official-label"):[];for(var i=0;i<labels.length;i++)if(text(labels[i].textContent)===label)return labels[i].parentElement||null;return null}
  function statusTextFromDom(section){var row=rowByLabel(section,"สถานะเรื่อง");if(!row)return"";var val=row.querySelector(".case-official-value");return text(val&&val.textContent)}
  function ensureReasonRow(section,value){if(!section)return null;var row=rowByLabel(section,"เหตุผล");if(row){var existingValue=row.querySelector(".case-official-value");if(existingValue&&value&&text(existingValue.textContent)!==value)existingValue.textContent=value;return existingValue||row}var grid=section.querySelector(".case-official-grid")||section;row=d.createElement("div");row.className="case-official-row";row.setAttribute("data-github-pending-reason-guard","r280");var label=d.createElement("div"),val=d.createElement("div");label.className="case-official-label";label.textContent="เหตุผล";val.className="case-official-value";val.textContent=value||"-";row.appendChild(label);row.appendChild(val);grid.appendChild(row);return val}
  function unwrapBundle(resp){var cur=resp;for(var i=0;i<8&&cur&&typeof cur==="object";i++){if(cur.case||cur.rawCase||cur.detail||cur.main)return cur;if(cur.data&&typeof cur.data==="object"){cur=cur.data;continue}break}return cur||{}}
  function fetchFreshReason(caseNum,target){caseNum=text(caseNum);if(!caseNum||!w.AppApi||typeof w.AppApi.call!=="function"||resolved[caseNum])return;resolved[caseNum]=true;if(inflight[caseNum])return;inflight[caseNum]=w.AppApi.call("apiGetCanonicalCaseBundle",{caseNum:caseNum,caseNo:caseNum,runningNo:caseNum,"ลำดับเรื่อง":caseNum,includeHistory:false,includeLetters:false,forceFresh:true,noCache:true,bypassCache:true,cacheTtlSeconds:0,source:"github-pending-reason-guard-r280"}).then(function(resp){var b=unwrapBundle(resp),reason=reasonFrom(b);if(target&&target.isConnected&&reason)target.textContent=reason;return reason},function(err){try{w.AppRuntime&&typeof w.AppRuntime.recordWarning==="function"&&w.AppRuntime.recordWarning("github.pendingReasonGuard.r280",err,{caseNum:caseNum})}catch(_e){}return""}).finally(function(){delete inflight[caseNum]})}
  function reconcile(){scheduled=false;var section=statusSection();if(!section)return;var bundle=bundleNow(),status=statusFrom(bundle)||statusTextFromDom(section);if(!isPending(status))return;var reason=reasonFrom(bundle),target=ensureReasonRow(section,reason||"-");if(!reason)fetchFreshReason(caseNumFrom(bundle),target)}
  function schedule(){if(scheduled)return;scheduled=true;(w.requestAnimationFrame||function(fn){return w.setTimeout(fn,0)})(reconcile)}
  if(typeof MutationObserver==="function"){var observer=new MutationObserver(schedule);function bind(){try{observer.observe(d.body||d.documentElement,{subtree:true,childList:true});schedule()}catch(_e){}}d.readyState==="loading"?d.addEventListener("DOMContentLoaded",bind,{once:true}):bind()}
  d.addEventListener("app:page-activated",schedule,false);d.addEventListener("app:page-reloaded",schedule,false);d.addEventListener("app:page-refreshed",schedule,false);
})(root,root.document);
})(typeof window!=="undefined"?window:globalThis);
